# Ficheiro de configuração para ligação à base de dados MSSQL
# utiliza-se ficheiro ini seprado, por oposição a colocar as credenciais no código fonte
# para maior segurança e facilidade de manutenção
[myMSSQLdb]
driver = ODBC Driver 18 for SQL Server
host = tcp:localhost,1433
db = biblioteca
user = sa
pass = YourStrong!Passw0rd
# pass = ClientS@fe!Passw0rd
encrypt = yes
trust_server_certificate = yes
